# Generated by Django 4.1.1 on 2022-11-26 19:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="RU"
            ),
        ),
    ]
