# Generated by Django 4.1.1 on 2023-01-07 22:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="RU", verbose_name="phone"
            ),
        ),
    ]
