# Generated by Django 4.1.1 on 2022-09-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(
                choices=[
                    ("Рязань", "Рязань"),
                    ("Тула", "Тула"),
                    ("Владимир", "Владимир"),
                ],
                default="",
                max_length=128,
                verbose_name="Город",
            ),
        ),
    ]
