# Generated by Django 4.1.1 on 2022-09-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(
                default="2022-09-20", verbose_name="Дата подачи авто"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="time",
            field=models.TimeField(default="20:22"),
            preserve_default=False,
        ),
    ]
