# Generated by Django 4.1.1 on 2022-09-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_date_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="airport",
            field=models.CharField(
                choices=[
                    ("Домодедово", "Домодедово"),
                    ("Внуково", "Внуково"),
                    ("Шереметьево", "Шереметьево"),
                    ("Жуковский", "Жуковский"),
                ],
                default="",
                max_length=64,
                verbose_name="Аэропорт",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.TimeField(verbose_name="Время подачи авто"),
        ),
    ]
