# Generated by Django 4.1.1 on 2022-11-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_airport_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.IntegerField(default=0, verbose_name="Номер"),
        ),
    ]
