# Generated by Django 4.1.1 on 2022-11-26 14:11

from time import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="departure_date",
            field=models.DateField(
                default='2022-02-11', verbose_name="Дата вылета"
            ),
            preserve_default=False,
        ),
    ]
