# Generated by Django 4.1.1 on 2022-10-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_airport_alter_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Статус заказа"
            ),
        ),
    ]
