# Generated by Django 4.1.1 on 2022-11-26 19:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_departure_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="RU"
            ),
        ),
    ]
