# Generated by Django 4.1.1 on 2022-10-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Статус заказа"),
        ),
    ]
