# Generated by Django 4.1.1 on 2022-10-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="flight_number",
            field=models.CharField(
                default="xxx", max_length=16, verbose_name="Номер рейса"
            ),
            preserve_default=False,
        ),
    ]
