# Generated by Django 4.1.1 on 2022-10-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_flight_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="departure_time",
            field=models.TimeField(default="22:22", verbose_name="Время вылета"),
            preserve_default=False,
        ),
    ]
