# Generated by Django 4.1.1 on 2023-01-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_telephone_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Город")),
                ("slug", models.SlugField(default="city", unique=True)),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.RemoveField(
            model_name="airport",
            name="start_price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="airport",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.AddField(
            model_name="airport",
            name="slug",
            field=models.SlugField(default="airport", unique=True),
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "airport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="orders.airport",
                        verbose_name="Аэропорт",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="orders.city",
                        verbose_name="Город",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.route",
                verbose_name="Маршрут",
            ),
        ),
    ]
