# Generated by Django 4.1.1 on 2023-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0008_city_remove_airport_start_price_remove_order_airport_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
