# Generated by Django 4.1.1 on 2022-10-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True, max_length=256, verbose_name="Комментарий"
            ),
        ),
    ]
