# Generated by Django 4.1.1 on 2022-10-13 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата подачи авто"
            ),
        ),
    ]
